FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/Mimima.Web.Api/Mimima.Web.Api.csproj", "src/Mimima.Web.Api/"]
RUN dotnet restore "src/Mimima.Web.Api/Mimima.Web.Api.csproj"
COPY . .
WORKDIR "/src/src/Mimima.Web.Api"
RUN dotnet build "Mimima.Web.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mimima.Web.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mimima.Web.Api.dll"]
